Add an ability to update timezone
fastiuk/sonic-host-services pull request #2
Opened 2023-03-22 18:38 UTC by fastiuk

2023-03-22 22:20 UTC, fastiuk commented
@Meir-renford, here is a host-service code

2023-03-30 00:08 UTC, dgsudharsan requested changes

2023-03-30 00:08 UTC, dgsudharsan commented on scripts/hostcfgd
> +        new_timezone = data.get('timezone')
Should have cache and compare against existing value to avoid calling this command for any update in device_metadata?

2023-03-30 17:38 UTC, fastiuk commented on scripts/hostcfgd
> +        new_timezone = data.get('timezone')
Make sense, will update

2023-04-11 01:05 UTC, dgsudharsan requested changes

2023-04-11 01:05 UTC, dgsudharsan commented on scripts/hostcfgd
> +            syslog.syslog(syslog.LOG_ERR,
This check mandates timezone config to be present in DEVICE_METADATA, else would throw error. I don't think its correct. It should be optional field.

2023-04-13 02:50 UTC, dgsudharsan approved these changes

2023-04-13 15:28 UTC, closed without merging